### ISSUE TITLE
Simvar lookup fails in WASimUI

### ISSUE THREAD

**Issue by kaosfere** [mpaperno/WASimCommander#12]
The functionality for simvar lookup doesn't seem to be functioning for me.   Example reproduction:

1. Launch the sim (currently testing on 1.30.7.0 but also happened on older versions.
2. Start any flight.
3. Connect to simulator in WASimUI, then connect to server.
4. Select the "SimulatorVariable" value in the dropdown next to the "Lookup" field.
5. Enter a string, such as "GPS", in the "Lookup" field and hit the magnifying glass.

Outcome:

Errors in the console.

> Lookup type SimulatorVariable failed for name "GPS"
> Lookup command returned Nak response.  Reason, if any: "Lookup type SimulatorVariable failed for name \\"GPS\\""

Expected result:

Search should return a list of many simvars containing "GPS" that, theoretically, would match the results of the same operation using the Simvar Watcher example program.

Tested on Windows 11 with the latest release version (1.1.0) of the WASim Commander community folder package and WASimUI.

**Comment by mpaperno** [comment]
Why is your expected result a list?  This is not a feature, there is no "fuzzy lookup" and nowhere is it documented that lookup returns multiple results (it cannot).  It literally just runs the corresponding Gauge API function  https://docs.flightsimulator.com/html/Programming_Tools/WASM/Gauge_API/get_aircraft_var_enum.htm  

If you want a queryable database of sim vars, check out my other project  https://github.com/mpaperno/MSFS-Tools/tree/main/MSFS-DocImport

**Comment by kaosfere** [comment]
Expected result was an inference from using other tools which do do simvar scraping -- A&O and Spad.Next both offer that feature, among others.  The collection of text box, search icon, and drop-down are easy to intuit as a comprehensive search option, especially if one has used other tools that provide that functionality.

Reckon this is just confusing UI design then, not a bug.

**Comment by mpaperno** [comment]
Inference from other tools...?  Not sure what this has to do with any other tools.  

There's an actual other part of the UI which returns _lists_.  If anything I'd expect a sim var choice in there, not in the lookup line which only has one text box for displaying the result. Also the UI is meant as a companion to the documented API/Client.

Anyway there is no way to query the simulator to return a name for a variable ID.  There [is for Local vars](https://docs.flightsimulator.com/html/Programming_Tools/WASM/Gauge_API/get_name_of_named_variable.htm), which is why we can return a list of those.

How do all these other tools "scrape" Sim Vars exactly?

**Comment by kaosfere** [comment]
> LOL, ok, well since you have a "dev staff" at your disposal, contributions are welcome!

I do, as a matter of fact.   I'm one of the co-founders of Working Title and have a team of a dozen+ developers working on the sim professionally on a daily basis, including access to game source code and direct communications with key folks at Asobo.   A number of us found WASim Commander a useful utility in our daily work and believed we'd identified a bug in it, so I thought I'd report that.

Given the attitude I've received in response I regret spending the time trying to be helpful.   With respect, you could benefit from being a little less cynical and a little more courteous to folks making well-intentioned bug reports.  We make a point to treat _our_ users that way, and I think our success on the platform shows that it's helpful.

Cheers.

**Comment by mpaperno** [comment]
You submitted an issue for what wasn't an issue -- you decided it was for some reason.  I explained that. You then tried to explain that it's a bug because "other tools do that." That's how it came across anyway.

When I tried to actually discuss the underlying issue (getting a list of Sim Vars), I was deemed to have an attitude.  Very helpful.

Your late edit about how "others" also saw it as a bug, apparently also because "other tools do that" was superfluous and rude IMHO.  This is a personal OS project with no backing and so far no external contributors, despite the fact that some "major players" as yourself apparently "find it useful." I pay MS for the pleasure of making tools for their software (and submitting bug reports too). If you want to point out how many resources you have available to you while complaining (twice) about some perceived lack on the part of my OS software project, I'm not sure how you expect me to react to that.

I do have it on my list to integrate the database of scraped sim vars and events from my other tool into WASimUI as a convenience, but it's a long list at this point.

Cheers,
-Max

**Comment by kaosfere** [comment]
You asked where the expected result came from.  I was answering that question, not insisting that you had a bug.  Believe me, I understand never-ending feature lists, and having folks insist things are my problem that are not.  In addition to being a professional developer I've been an open source dev for two decades and I know how it goes. None of that was my intention here.  

As for the rest, I have no intention of getting into a public pissing match with you.   I mentioned my credentials because you felt the need to quote my "dev team" back to me in its own sneering single-line response with scare quotes.  (And you want to talk about rudeness?)  That deserved a response.

I made a bug report, it's apparently not a bug, and for the sake of civility I'll write the rest off as a misunderstanding.

Good luck with the project.

**Comment by mpaperno** [comment]
> Reckon this is just confusing UI design then, not a bug.

Kinda funny way of "not insisting" on something.  I'm sorry you were confused.

You wrongly decided that "lookup" should for some reason return a list (I still don't understand why), and just refuse to acknowledge it.  The tooltip even clearly says "Lookup the ID of a variable or unit."  As in singular.

Magnanimous of you to write it off though, thanks.  Oh and you're welcome for making the tool useful (if confusing) in the first place.

**Comment by kaosfere** [comment]
Nice, I offer a fig-leaf and you continue with the snark.   Some folks just don't know when to quit.  😆  That's OK, I do. 

Once again, and with all deserved sincerity, good luck with the project.
